AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a VPC
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: Lab VPC
Outputs:
  VPC:
    Description: VPC
    Value: !Ref VPC
    Export:
      Name: MYVPC