Resources:
  RobotAppServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-087c17d1fe0178315
      SecurityGroups:
      - !Ref RobotAppSecurityGroup
      UserData:
        Fn::Base64: |-
          #!/bin/bash -xe 
          yum install httpd -y
          service httpd start
          systemctl enable httpd
  RobotAppSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
Outputs:
  RobotAppServerPublicIP:
    Description: 'Public DNS of RobotAppServer EC2 instance'
    Value: !GetAtt RobotAppServer.PublicIp
