Parameters:
  InstanceType:
    Type: 'String'
    Default: 't3.micro'
    AllowedValues: ['t3.micro', 't2.micro']
    Description: 'Instance Type'
Mappings: 
  AWSRegionToAMI: 
      us-east-1:
        AMI: ami-c58c1dd3 
      us-east-2:
        AMI: ami-4191b524 
      us-west-1:
        AMI: ami-7a85a01a 
      us-west-2:
        AMI: ami-4836a428 
      ca-central-1:
        AMI: ami-0bd66a6f 
      eu-west-1:
        AMI: ami-01ccc867 
      eu-west-2:
        AMI: ami-b6daced2 
      eu-central-1:
        AMI: ami-b968bad6 
      sa-east-1:
        AMI: ami-37cfad5b 
      ap-southeast-1:
        AMI: ami-fc5ae39f 
      ap-southeast-2:
        AMI: ami-162c2575 
      ap-south-1:
        AMI: ami-52c7b43d 
      ap-northeast-1:
        AMI: ami-923d12f5 
      ap-northeast-2:
        AMI: ami-9d15c7f3 
Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap
        - AWSRegionToAMI
        - !Ref 'AWS::Region'
        - AMI
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - 'sg-0e25385aa0c51b01b'
          SubnetId: 'subnet-0f9cdd409780a6631'
      UserData:
        Fn::Base64: |-
          #!/bin/bash -xe
          yum install httpd -y
          echo "<!DOCTYPE html><body><h1>Hola soy el Webserver </h1></body></html>" > /var/www/html/index.html
          service httpd start
          systemctl enable httpd
Outputs:
  PublicIp:
    Value: !GetAtt WebServer.PublicIp     
  

