MySecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Allow http Connections
    SecurityGroupIngress:
      - IpProtocol: tcp
        fromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
MyInstance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t3.small
    ImageId: ami-0ae0f14cea4998f46
    SecurityGroups:
      - !Ref MySecurityGroup
