Resources:
  BucketPepito:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'jumpingbrains909090'
  InstanceJuanita:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.small'
      ImageId: 'ami-0ae0f14cea4998f46'