Resources:
  BucketPepito:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'jumpingbrains'
    DependsOn: InstanceJuanita
  InstanceJuanita:
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't3.micro'
      ImageId: 'ami-0ae0f14cea4998f46'
      UserData:
        Fn::Base64: !Sub |-
          #!/bin/bash -xe 
          yum install httpd -y
          sleep 60
          service httpd start
          systemctl enable httpd
          /opt/aws/bin/cfn-signal -e $? 
          --stack ${AWS::StackId} --resource InstanceJuanita --region ${AWS::Region}