Resources:
  MyNACLforEC2DevSubnet:
    Type: AWS::EC2::NetworkAcl
      Properties:
        VpcId: "vpc-076344f09c685bbfd"
  InboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: MyNACL
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 172.16.0.0/24
       PortRange:
         From: 22
         To: 22