Resources:
  myVPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
       - Key: "Name"
         Value: "ProductionVPC"
  mySubnet: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: 
        !Ref myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: "eu-south-2"
