Parameters:
  Project:
    Type: "AWS::SSM::Parameter::Value<String>"
    Description: "Company Project"
    Default: "/company/projects/project"
  LatestAMIID:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Description: "Latest AMI Image"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
Resources:
  Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t3.micro"
      ImageId: !Ref LatestAMIID
      Tags:
        - Key: "company:project"
          Value: !Ref Project
