Resources:
  MySecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http Connections
      SecurityGroupIngress:
        - IpProtocol: tcp
          fromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MySGSubnetRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL Connections from the EC2 Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          fromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt MySecurityGroupEC2.GroupId
