 InstanceType:
    Type: 'String'
    Default: 't3.micro'
    AllowedValues: ['t3.micro', 't2.micro']
    Description: 'Instance Type'
  LatestAMIID:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Description: 'Latest AMI Image'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'