apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: processor
            operator: NotIn
            values:
            - gpu            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
