apiVersion: v1
kind: Pod
metadata:
 labels:
  app: redis
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - redis
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: redis-server
    image: redis:3.2-alpine 

