apiVersion: v1
kind: Pod
metadata:
 name: podwithebs
 namespace: santander
 labels:
  app: web
spec:
  containers:
  - name: web-app
    image: nginx:1.12-alpine
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
     claimName: app-pvc
~:q!
