apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: santander
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi