apiVersion: v1
kind: Pod
metadata:
 #name: web-app
 generateName: web-app-
 labels:
  app: example
 annotations:
  description: "Mi super aplicacion web"
  owner: "Reynaldo Luevano"
spec:
  containers:
  - name: web-app-container
    image: nginx:1.12-alpine
    ports:
    - containerPort: 80
      protocol: TCP
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zproc
            operator: In
            values:
            - gpu      