apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: web-app-container
        image: nginx:1.12-alpine
        ports:
        - containerPort: 80
          protocol: TCP

