#!/bin/bash

sed -i -e "s/STAGE_VALUE/$DEPLOYMENT_GROUP_NAME/" /var/www/html/index.html

export VERSION="$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query "deploymentInfo.description" --output text)"

sed -i -e "s/APP_VERSION/$VERSION/" /var/www/html/index.html

export TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60"`

export INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: ${TOKEN}" -s http://169.254.169.254/latest/meta-data/instance-id)

sed -i -e "s/INSTANCE_ID/$INSTANCE_ID/" /var/www/html/index.html