apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
metadata:
  name: myEKScluster
  region: eu-west-1
  version: "1.32"
  tags:
    created-by: jumpingbrains
    env: development
iam:
  withOIDC: true
vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
  - name: vpc-cni
    version: 1.19.3
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true", "nodeAgent": {"enablePolicyEventLogs": "true"}}'
    resolveConflicts: overwrite
managedNodeGroups:
  - name: default
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    instanceType: m5.large
    privateNetworking: true
    releaseVersion: "1.32.3-20250519"
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      workshop-default: "yes"
